eureka:
    client:
    fetchRegistry: "true"
    registryFetchIntervalSeconds: "5"
    serviceUrl:
        defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: "true"
management:
    endpoints:
    web:
        exposure:
        include: '*'
