application:
    name: client-service-app
server:
    port: "0"
management:
    endpoints:
    web:
        exposure:
        include: '*'
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/db
        username: client
        password: client
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                temp:
                    use_jdbc_metadata_defaults: "false"
                default_schema: public
                show_sql: "false"
                use_sql_comments: "false"
                format_sql: "true"
                type: trace
        hibernate:
            ddl-auto: create-drop
            
